import Link from 'next/link';

export const metadata = {
  title: "The Colportage Association | Charles Spurgeon",
  description: "Discover how the Metropolitan Tabernacle Colportage Association and Susannah Spurgeon's Book Fund spread Christian literature across England.",
  keywords: ["Charles Spurgeon", "Colportage Association", "Literature Distribution", "Susannah Spurgeon", "Book Fund", "Evangelism", "Literature", "preacher"],
};

export default function TheColportageAssociationPage() {
  return (
    <div className="container" style={{ padding: '4rem 2rem', minHeight: '80vh', maxWidth: '800px', margin: '0 auto' }}>
      <Link href="/en/about/preacher" style={{ color: 'var(--text-muted)', textDecoration: 'none', marginBottom: '2rem', display: 'inline-block' }}>
        &larr; Back to The Preacher & His Work
      </Link>
      
      <article className="sermon-content">
        <header style={{ marginBottom: '3rem', textAlign: 'center' }}>
          <div style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '1rem', textTransform: 'uppercase', letterSpacing: '1px' }}>
            April 5, 2026 • 5 min read
          </div>
          <h1 className="title-gold" style={{ fontSize: '2.5rem', marginBottom: '1.5rem', lineHeight: '1.2' }}>
            The Colportage Association: The Network of Christian Book Distributors on the Streets
          </h1>
        </header>

        <div style={{ lineHeight: '1.8', fontSize: '1.1rem', color: 'var(--text-primary)', textAlign: 'justify' }}>
          
          <h3 style={{ color: 'var(--accent)', marginTop: '2.5rem', marginBottom: '1rem', fontFamily: 'var(--font-serif)', fontSize: '1.5rem' }}>The Power of the Printed Page</h3>
          <p style={{ marginBottom: '1.5rem' }}>
            Charles Haddon Spurgeon understood that while his powerful voice could command the attention of thousands within the walls of the Metropolitan Tabernacle, the printed page possessed the unique ability to transcend geographical boundaries and enter the homes of those who would never attend a church service. To combat the rising tide of cheap, secular, and often heterodox literature circulating in Victorian England, Spurgeon realized the absolute necessity of a mobilized, grassroots force of literature distributors who could bring the truth directly to the people.
          </p>

          <h3 style={{ color: 'var(--accent)', marginTop: '2.5rem', marginBottom: '1rem', fontFamily: 'var(--font-serif)', fontSize: '1.5rem' }}>The Foundation of the Colportage Association</h3>
          <p style={{ marginBottom: '1.5rem' }}>
            In direct connection with the evangelistic zeal generated by the Pastors' College, the Metropolitan Tabernacle Colportage Association was established. The colporteurs were essentially traveling evangelists and book salesmen who walked the streets, visiting rural villages, country lanes, and urban slums alike. Their primary mission was the evangelization and distribution of sound theological material. They sold Bibles, good Puritan books, and Spurgeon's own printed sermons at highly affordable prices, while also distributing free gospel tracts to the poorest citizens.
          </p>

          <h3 style={{ color: 'var(--accent)', marginTop: '2.5rem', marginBottom: '1rem', fontFamily: 'var(--font-serif)', fontSize: '1.5rem' }}>Evangelism from Door to Door</h3>
          <p style={{ marginBottom: '1.5rem' }}>
            These men were not merely traveling merchants; they were frontline missionaries. As they went from house to house, they engaged individuals in personal conversations about their souls and the Gospel of Jesus Christ. The association grew steadily and proved to be a highly effective evangelistic machine. By the year 1891, the Colportage Association employed 96 active colporteurs spreading the Gospel throughout the country. Through this vast network, Spurgeon ensured that the working-class people of England had access to literature that would edify their souls and point them to the Savior.
          </p>

          <h3 style={{ color: 'var(--accent)', marginTop: '2.5rem', marginBottom: '1rem', fontFamily: 'var(--font-serif)', fontSize: '1.5rem' }}>Susannah Spurgeon's Book Fund</h3>
          <p style={{ marginBottom: '1.5rem' }}>
            Complementing this massive effort of grassroots literature distribution was the extraordinary and highly impactful work of Spurgeon's wife, Susannah. Recognizing that many rural pastors and nonconformist ministers were too impoverished to afford the theological books necessary for their own pastoral study and sermon preparation, Susannah inaugurated the "Book Fund" in 1875. 
          </p>
          <p style={{ marginBottom: '1.5rem' }}>
            Despite suffering from severe gynecological health issues that required surgery in 1869 and left her as a virtual invalid for the remainder of her life, Susannah tirelessly managed this charity directly from her home. Her unwavering support for her husband's ministry and her commitment to the glory of God drove her to supply impoverished ministers with robust theological libraries. By the time of her death in October 1903, the Book Fund had successfully distributed an astonishing 200,000 theological books to needy pastors across the nation.
          </p>

          <h3 style={{ color: 'var(--accent)', marginTop: '2.5rem', marginBottom: '1rem', fontFamily: 'var(--font-serif)', fontSize: '1.5rem' }}>A Lasting Literary Legacy</h3>
          <p style={{ marginBottom: '1.5rem' }}>
            Through the Colportage Association reaching the common people on the streets, and Susannah's Book Fund equipping the shepherds in the pulpits, the Spurgeons ensured that robust, Reformed, and Puritan theology saturated the British landscape. They practically demonstrated that a well-read congregation and a well-equipped, biblically grounded ministry were the greatest bulwarks against the theological decline of their era.
          </p>

          <hr style={{ border: 'none', borderTop: '1px solid var(--border)', margin: '3rem 0' }} />

          {/* BIBLIOGRAPHY */}
          <details className="sermon-tags-details" style={{ marginBottom: '1.5rem' }}>
            <summary className="sermon-tags-summary" style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>
              <span>Bibliography & Sources</span>
              <span className="sermon-tags-icon">▼</span>
            </summary>
            <div className="sermon-tags-content" style={{ marginTop: '1rem' }}>
              <ol style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', paddingLeft: '1.5rem', lineHeight: '1.6' }}>
                <li style={{ marginBottom: '0.5rem' }}>Wikipédia, a enciclopédia livre. "Charles Spurgeon." Accessed July 14, 2026. <a href="https://pt.wikipedia.org/wiki/Charles_Spurgeon" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>Link</a>.</li>
                <li style={{ marginBottom: '0.5rem' }}>Biblioteca Charles Spurgeon. "Quem foi Charles Spurgeon?" <em>SpurgeonLine</em>. Accessed July 14, 2026. <a href="https://spurgeonline.com.br/artigos/quem-foi-charles-spurgeon/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>Link</a>.</li>
                <li style={{ marginBottom: '0.5rem' }}>Projeto Spurgeon. "Quem Foi Charles Haddon Spurgeon?" <em>Projeto Spurgeon: Proclamando a Cristo Crucificado</em>. Accessed July 14, 2026. <a href="https://www.projetospurgeon.com.br/quem-foi-spurgeon/quem-foi-charles-haddon-spurgeon/" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>Link</a>.</li>
                <li style={{ marginBottom: '0.5rem' }}>Wikipédia, a enciclopédia livre. "Susannah Spurgeon." Accessed July 14, 2026. <a href="https://pt.wikipedia.org/wiki/Susannah_Spurgeon" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent)' }}>Link</a>.</li>
                <li style={{ marginBottom: '0.5rem' }}>Rhodes, Ray. <em>Susie: The Life and Legacy of Susannah Spurgeon, wife of Charles H. Spurgeon</em>. Chicago: Moody Publishers, 2018. Cited in "Susannah Spurgeon," <em>Wikipédia, a enciclopédia livre</em>.</li>
                <li style={{ marginBottom: '0.5rem' }}>Matos, Alderi Souza de. "Tesouro em vaso de barro: Charles Spurgeon e a palavra encarnada, escrita e proclamada." <em>Fides Reformata</em> 26, no. 2 (2021): 9-25.</li>
              </ol>
            </div>
          </details>

          {/* TAGS */}
          <details className="sermon-tags-details" style={{ marginBottom: '2rem' }}>
            <summary className="sermon-tags-summary" style={{ fontSize: '1.1rem', fontWeight: 'bold' }}>
              <span>Article Tags</span>
              <span className="sermon-tags-icon">▼</span>
            </summary>
            <div className="sermon-tags-content" style={{ marginTop: '1rem', display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
              {["Colportage Association", "Literature Distribution", "Susannah Spurgeon", "Book Fund", "Evangelism", "Literature"].map((tag) => (
                <span key={tag} className="sermon-tag" style={{ background: 'var(--surface-hover)', padding: '0.3rem 0.8rem', borderRadius: '15px', fontSize: '0.85rem', border: '1px solid var(--border)' }}>
                  {tag}
                </span>
              ))}
            </div>
          </details>

          {/* PAGINATION */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '3rem', paddingTop: '2rem', borderTop: '1px solid var(--border)' }}>
            <Link href="/en/about/preacher/the-stockwell-orphanage" style={{ textDecoration: 'none' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '0.3rem' }}>&larr; Previous Article</span>
              <span style={{ color: 'var(--accent)', fontFamily: 'var(--font-serif)', fontSize: '1.2rem', fontWeight: 'bold' }}>The Stockwell Orphanage</span>
            </Link>
            <Link href="/en/about/preacher/homiletics" style={{ textDecoration: 'none', textAlign: 'right' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '0.3rem' }}>Next Article &rarr;</span>
              <span style={{ color: 'var(--accent)', fontFamily: 'var(--font-serif)', fontSize: '1.2rem', fontWeight: 'bold' }}>Homiletics</span>
            </Link>
          </div>

        </div>
      </article>
    </div>
  );
}
