import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const publicData = path.join(ROOT, 'public', 'data');
const contentData = path.join(ROOT, 'content', 'data');

async function copyDir(src, dest) {
  try {
    await fs.mkdir(dest, { recursive: true });
    const entries = await fs.readdir(src, { withFileTypes: true });

    for (let entry of entries) {
      const srcPath = path.join(src, entry.name);
      const destPath = path.join(dest, entry.name);

      if (entry.isDirectory()) {
        await copyDir(srcPath, destPath);
      } else {
        await fs.copyFile(srcPath, destPath);
      }
    }
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.error(`Error copying ${src} to ${dest}:`, err);
    }
  }
}

async function main() {
  console.log('--- Preparing Content for Vercel Serverless Functions ---');
  await copyDir(publicData, contentData);
  
  // Also copy root JSON files from public/ (generated by some scripts there)
  try {
    await fs.copyFile(path.join(ROOT, 'public', 'search-index.json'), path.join(ROOT, 'content', 'search-index.json'));
  } catch(e) {}
  
  try {
    await fs.copyFile(path.join(ROOT, 'public', 'articles-index.json'), path.join(ROOT, 'content', 'articles-index.json'));
  } catch(e) {}
  
  console.log('Content preparation complete.');
}

main().catch(console.error);
